# Generated by Django 3.1.7 on 2021-02-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serviço',
            new_name='Servicos',
        ),
    ]
