# Generated by Django 3.1.7 on 2021-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210225_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='servico',
            field=models.CharField(max_length=100, verbose_name='Servicos'),
        ),
    ]
