# Generated by Django 3.1.7 on 2021-02-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210225_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('servicos', models.CharField(max_length=100, verbose_name='Servico')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-status-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=13, verbose_name='Icone')),
            ],
            bases=('core.base',),
        ),
        migrations.RenameModel(
            old_name='Cargos',
            new_name='Cargo',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='cargo',
            new_name='cargos',
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
    ]
