# Generated by Django 3.1.7 on 2021-02-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210225_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('features', models.CharField(max_length=100, verbose_name='feature')),
                ('descricao', models.TextField(max_length=100, verbose_name='descricao')),
                ('icon', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'note e cel'), ('lni-leaf', 'folha'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete')], max_length=17, verbose_name='Icon')),
            ],
            bases=('core.base',),
        ),
    ]
