# Generated by Django 3.1.7 on 2021-02-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
    ]
